[build]
target = "x86_64-unknown-uefi"
rustflags = [
    "-C", "target-feature=-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-avx512f,-avx512bw,-avx512cd,-avx512dq,-avx512vl,-f16c,-fma,-fxsr",
    "-C", "no-redzone",
]
